modules/class_optimize.py
- removed unused functions
- restructure code -optimized parameters of optimization
=> restructure and optimization of class_optimize.py

.gitignore, README-DE.md, README.md
Moving german readme to READEME-DE.md. Add sensible gitignore defaults for most operating systems, VS code and Python.
=> Translate README to English

modules/class_optimize.py
Reverts Akkudoktor-EOS/EOS#60
Optimierung funktioniert nicht mehr, die Ergebnisse sind falsch. Randbedingungen werden nicht mehr eingehalten. 
Sorry erst später gemerkt.
=> Revert "restructure and optimization of class_optimize.py"

modules/class_ems.py
Fixes #56
Speed durch np arrays und ein paar Schleifenoptimierungen ca. verdreifacht
=> Performance

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/developer.yml, .github/ISSUE_TEMPLATE/enhancement.yml, CONTRIBUTING.md, README.md, flask_server.py, tests/test_class_ems.py
There are generators for `CONTRIBUTING.md`, but I tried to keep things much shorter than you'd usually have for big, mature projects.
The issue templates should help to keep the tickets a bit more organized.
@drbacke the `CONTRIBUTING.md` is probably the place where you should clarify the guard rails for contributions.
At some point I would also suggest to create a `GOVERNANCE.md` to clarify how decisions are made (ultimately by @drbacke).
=> Add contribution guide and issue templates

modules/visualize.py
datetime.datetime.now() is incorrectly accessing the datetime class
=> bugfix visualize module

config.py, flask_server.py
MariaDB is completely removed from the project
=> MariaDB removed - Unittest class_optimize skipped per default

flask_server.py, modules/class_optimize.py, single_test_optimization.py, tests/test_class_ems.py, tests/test_class_optimize.py
- min soc for pv battery 
- unit tests corrected and tests with min_soc
=> min_soc (was killed by someone else, pls dont force push!)

README-DE.md
Habe meine Probleme beim erstellen des Pull Requests bewältigt. Danke für deine Geduld @drbacke !
Closes issue #82.
=> date fix line 110 README-DE.md

pyproject.toml, src/akkudoktoreos/class_akku.py, src/akkudoktoreos/class_ems.py, src/akkudoktoreos/class_haushaltsgeraet.py, src/akkudoktoreos/class_inverter.py, src/akkudoktoreos/class_load.py, src/akkudoktoreos/class_load_container.py, src/akkudoktoreos/class_load_corrector.py, src/akkudoktoreos/class_optimize.py, src/akkudoktoreos/class_pv_forecast.py, src/akkudoktoreos/class_soc_calc.py, src/akkudoktoreos/class_sommerzeit.py, src/akkudoktoreos/class_strompreis.py, src/akkudoktoreos/config.py, src/akkudoktoreos/heatpump.py, src/akkudoktoreos/visualize.py, src/akkudoktoreosserver/flask_server.py, tests/test_class_akku.py, tests/test_class_ems.py, tests/test_class_optimize.py
This was in discussion before the big rebase.
Just line-length expansion and a simple `ruff format`
=> Extend line length

.github/workflows/pytest.yml, .gitignore, .pre-commit-config.yaml, .vscode/extensions.json, .vscode/settings.shared.json, CONTRIBUTING.md, Makefile, README.md, docker-compose.yaml, pyproject.toml
A suggestion for some vscode configuration to improve the workflow.
=> Add settings and extension recommendations

src/akkudoktoreos/class_sommerzeit.py, src/akkudoktoreos/visualize.py
* Currently prediction hours are relative from current hour and don't adjust on daylight saving change.
* ist_dst_wechsel now unused.
=> visualize: Keep shape of plots the same on dst change Closes #185

src/akkudoktoreos/class_optimize.py
* mate -> cxTwoPoints needs at least two elements.
=> optimize: Enforce start solution with at least two elements Closes #205

Makefile, docs/akkudoktoreos/serverapi.rst
* Fix swagger link in sphynx docs.
=> Fix docs creation Closes #218

.pre-commit-config.yaml
* Install missing deps. In the future we probably just want to reuse the dev environment (e.g. poetry shell) to have same result for hook and explicit execution in venv.
=> pre-commit: Fix mypy hook

src/akkudoktoreos/optimization/genetic.py, src/akkudoktoreos/prediction/price_forecast.py
Awattar Price changed to more precise value; if SoC=0 discharge =1 forced. Exp Avg for siple Price Forecast
=> Awattar Price changed to more precise value; if SoC=0 discharge =1 forced. Exp Avg for siple Price Forecast

src/akkudoktoreos/devices/heatpump.py, tests/test_heatpump.py
minor corrections and some translations
=> heatpump translated

docs/akkudoktoreos/openapi.json, src/akkudoktoreos/optimization/genetic.py, src/akkudoktoreos/prediction/pv_forecast.py, src/akkudoktoreos/utils/visualize.py, tests/test_pv_forecast.py, tests/testdata/pv_forecast_input_1.json
* temperature, relativehumidity_2m, windspeed_10m can be null
* prettify pv_forecast_input_1.json (and add null value)
=> pvforecast: Some values optional. Closes #292

README.md, pyproject.toml
Numpy needs 3.10 see #297
https://numpy.org/devdocs/release/2.2.0-notes.html
"This release supports Python versions 3.10-3.13."
=> python version 3.10 for feature branch

tests/test_server.py
see https://github.com/Akkudoktor-EOS/EOS/issues/299#issuecomment-2565938582
=> temp. skip test_server

src/akkudoktoreos/prediction/elecpriceakkudoktor.py, tests/test_elecpriceakkudoktor.py, tests/testdata/elecpriceforecast_akkudoktor_1.json
Fix URL in elecprice -> no day ahead data
=> Fix URL in elecprice

single_test_optimization.py, src/akkudoktoreos/optimization/genetic.py, src/akkudoktoreos/utils/visualize.py
Added: A new plot displaying the minimum, maximum, and average fitness of the optimization process across generations.
Why: This plot helps analyze the performance of optimization runs:
- If the chart stabilizes towards the end with minimal changes, it indicates convergence.
- If the minimum fitness value reaches its optimal value quickly, the number of generations (ngen) can potentially be reduced to save computation time.
- Conversely, a lack of stabilization may suggest the optimization did not achieve satisfactory results.
graph for single_test_optimization.py:
=> Feature Branch: Generation Fitness plot

docs/_generated/openapi.md, openapi.json, src/akkudoktoreos/server/eos.py
Legacy endpoint gesamtlast_simple expected yearly energy consumption to be given in Wh SI units.
Closes #368
=> Fix gesamtlast_simple

src/akkudoktoreos/core/dataabc.py, src/akkudoktoreos/server/eos.py
Make Gesamtlast endpoint understand the legacy load measurement data format.
Closes #367
=> Fix Gesamtlast

single_test_optimization.py, src/akkudoktoreos/utils/visualize.py
adds the option to create png's of the created charts in the output dict.
This is in preparation for eosdash
when initializing VisualizationReport "create_png" must be set true.
Charts from single_test_optimization.py:
=> Pics or it didn't happen

src/akkudoktoreos/core/ems.py, tests/test_class_ems_2.py
Added data and object pre-fetching for `def simulate`.
Some code cleanup
10% better runtime for single_test_optimization.py.
extended tests and some comment maintenance there.
=> Data prefetch for ems

src/akkudoktoreos/devices/heatpump.py, src/akkudoktoreos/optimization/genetic.py, src/akkudoktoreos/utils/visualize.py
replacing logging with our own class.
=> replacing import logging with .core.logging

.pre-commit-config.yaml, docs/akkudoktoreos/architecture.md, docs/akkudoktoreos/configuration.md, docs/akkudoktoreos/integration.md, docs/akkudoktoreos/measurement.md, docs/akkudoktoreos/optimization.md, docs/akkudoktoreos/prediction.md, docs/develop/getting_started.md, docs/index.md, docs/pymarkdown.json, docs/welcome.md
Add Markdown linter (pymarkdown) to pre-commit.
Adapt current markdown files to fulfill linter rules.
=> Add Markdown linter

.github/workflows/docker-build.yml
=> Workflow: Docker build on all PRs

.pre-commit-config.yaml, pyproject.toml, src/akkudoktoreos/core/dataabc.py, src/akkudoktoreos/server/eos.py, tests/conftest.py, tests/test_battery.py, tests/test_class_ems.py, tests/test_class_ems_2.py, tests/test_dataabc.py, tests/test_predictionabc.py, tests/test_server.py
updates components of pre-commit.
changes to pyproject.toml to ignore  "error: Unused "type: ignore" comment  [unused-ignore]"
type: ignore used for linux and windows commands
=> pre-commit update and ignore changes

src/akkudoktoreos/server/dash/demo.py
=> EOSdash: Add load figure to demo page.

requirements.txt
manual updates for dev branch only modules
=> Update requirements.txt for dev branch

docs/_generated/openapi.md, openapi.json, src/akkudoktoreos/config/config.py, src/akkudoktoreos/core/ems.py, src/akkudoktoreos/prediction/elecprice.py, src/akkudoktoreos/prediction/load.py, src/akkudoktoreos/prediction/pvforecast.py, src/akkudoktoreos/prediction/weather.py, src/akkudoktoreos/server/dash/admin.py, src/akkudoktoreos/server/dash/bokeh.py, src/akkudoktoreos/server/dash/components.py, src/akkudoktoreos/server/dash/configuration.py, src/akkudoktoreos/server/eos.py, src/akkudoktoreos/server/eosdash.py, tests/test_elecpriceimport.py, tests/test_pvforecastimport.py, tests/test_weatherclearoutside.py, tests/test_weatherimport.py
Improve config page to edit actual configuration used by EOS.
Add admin page to save the actual configuration to the configuration file.
=> EOSdash: Enable EOS configuration by EOSdash.

docs/_generated/openapi.md, openapi.json, src/akkudoktoreos/config/config.py, src/akkudoktoreos/core/ems.py, src/akkudoktoreos/prediction/elecprice.py, src/akkudoktoreos/prediction/load.py, src/akkudoktoreos/prediction/loadakkudoktor.py, src/akkudoktoreos/prediction/pvforecast.py, src/akkudoktoreos/prediction/weather.py, src/akkudoktoreos/server/dash/admin.py, src/akkudoktoreos/server/dash/bokeh.py, src/akkudoktoreos/server/dash/components.py, src/akkudoktoreos/server/dash/configuration.py, src/akkudoktoreos/server/eos.py, src/akkudoktoreos/server/eosdash.py, tests/test_elecpriceimport.py, tests/test_pvforecastimport.py, tests/test_weatherclearoutside.py, tests/test_weatherimport.py
Fixes #428
Waits for #477 to be merged.
=> Fix negative values load mean adjusted

src/akkudoktoreos/prediction/weatherclearoutside.py
=> chore: update weatherclearoutside.py

docs/_generated/openapi.md, openapi.json, requirements-dev.txt, requirements.txt
=> update(pydantic): Bump pydantic to 2.11.3

src/akkudoktoreos/prediction/pvforecastakkudoktor.py, tests/test_pvforecastakkudoktor.py, tests/testdata/pv_forecast_input_single_plane.json
If there is only a single plane the validation of the response fails with:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\rompic\Desktop\EOS\src\akkudoktoreos\prediction\pvforecastakkudoktor.py", line 432, in <module>
forecast.update_data()
File "C:\Users\rompic\Desktop\EOS\src\akkudoktoreos\prediction\predictionabc.py", line 217, in update_data
self._update_data(force_update=force_update)
File "C:\Users\rompic\Desktop\EOS\src\akkudoktoreos\prediction\pvforecastakkudoktor.py", line 292, in _update_data
akkudoktor_data = self._request_forecast(force_update=force_update)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\rompic\Desktop\EOS\src\akkudoktoreos\core\cache.py", line 978, in …
```
=> fix: pvforecast fails when there is only a single plane

docs/_generated/config.md, docs/akkudoktoreos/prediction.md, openapi.json, src/akkudoktoreos/prediction/elecprice.py, src/akkudoktoreos/prediction/elecpriceenergycharts.py
Added a configurable vat_rate, to provide more flexibility and enable users in different countries to configure the vat rate for their country.
The default is still 1.19
=> add configurable VAT rate for electricity price calculations
