modules/class_optimize.py
modules/visualize.py

- Optimized Imports: Removed unused imports and organized them.
- Refactored Code: Introduced split_individual function for clarity.
- Improved Efficiency: Enhanced penalty calculation and streamlined loops.
- Updated Evaluation Logic: Better handling of penalties in evaluate.
- Type Hints added.
Notes:
- Fixed seed option added for automated tests
- Verbose option added, default False
- isfloat is only used in flask_server.py
- start_hour is not used in this class
- identical results with the old version using test.py and fixed seeds

Refactored class_optimize.py

---

.dockerignore
.github/workflows/docker-build.yml
Dockerfile
config.py
modules/class_optimize.py
requirements.txt

In this PR I have adjusted the dockerfile a bit, to retain some disk space.
This is the part where I am the most uncertain if I broke something, as I am not running EOS my own and just getting into the project a bit.
I did see that upon uninstalling unused packages it did uninstall the mysql/mariadb libraries, so I re-added those by tagging them as manually installed.
Also I added multi arch container image building upon release creation which then push to the github container registry and allow easier distribution of the software for docker/containerd/k8s users.
Let me know what you think or what needs adjustments to work well.

Add multi-arch container build

---

single_test_optimization.py
tests/test_class_optimize.py

sets the seed for random to a fixed value to be able to compare results. Value chosen for obvious reason. Same value is used in the test case.

fixed_seed for single_test_optimization

---

README-DE.md
README.md
src/akkudoktoreos/class_optimize.py
src/akkudoktoreosserver/flask_server.py

fixing #126 by adding case "None", stings with whitespace and special types like +-inf.
Also moving the function to the server since its only used there.

improve and move isfloat(num)

---

src/akkudoktoreos/class_ems.py
tests/test_class_ems.py

replace_nan_with_none(data) is not needed anymore since we don't have any NaN values. Another 13% speed increase.

remove unused function

---

single_test_optimization.py
src/akkudoktoreos/class_ems.py
src/akkudoktoreos/class_haushaltsgeraet.py
src/akkudoktoreos/class_optimize.py
src/akkudoktoreosserver/flask_server.py
tests/test_class_ems.py

Big Bugfix - not sure if everything works again now.

[BUG]: class_ems nd_array not JSON serializable

---

.github/workflows/pytest.yml

Run tests after merging

---

tests/conftest.py

Startup of the test server is detected by a scan on the server logging output to stdout. 
Startup was triggered on the beginning of the log output. This is too early as on GitHub it takes longer than on a home machine until the server accepts connects.
Startup is now detected on the late log output.
Fixes #152

Fix test server startup detection.

---

NOTICE
pyproject.toml
src/akkudoktoreos/class_sommerzeit.py
src/akkudoktoreos/class_strompreis.py

* Timezone support comes with the standard lib since 3.9
Remove unlisted dependency pytz. If we want to keep it (comes as transitive dep atm), then we should put it into requirements.txt.

Replace pytz with stdlib zoneinfo/timezone, Bump python to 3.9

---

.github/workflows/pytest.yml
.gitignore
CONTRIBUTING.md
Dockerfile
Makefile
docker-compose.yaml
requirements-dev.txt
requirements.txt
src/akkudoktoreos/config.py
src/akkudoktoreos/visualize.py
src/akkudoktoreosserver/flask_server.py
tests/test_class_optimize.py

* Dockerfile: Use non-root user, buildx cache, setup for readonly container, remove unused apt deps. For now don't install pip package and keep development flask server as this will be replaced in the future (fastapi). Then a proper webserver (e.g. nginx) should be used and the pip package can be created and deployed just to the run-stage (with the webserver).
* docker-compose: Set to readonly (anonymous volumes declared in Dockerfile should maintain all writable data). Mount config.py for easier development. Should be replaced by environment support for all config file variables.
* Remove now unused class_soc_calc.
* Remove unused runtime dependencies: mariadb, joblib, pytest, pytest-cov.
* Move pytest-cov to dev dependencies.
* Update docs.

Streamline Dockerfile, remove unused deps and code

---

tests/test_pv_forecast.py

The 'other_timezone' fixture does not work on Windows. Skip the test case.
@NormannK experienced problems when testing on Windows (see #192). This PR should fix that.

Skip test for pv forecast timezone behaviour on Windows.

---

docs/akkudoktoreos/openapi.json
src/akkudoktoreos/prediction/elecprice.py
src/akkudoktoreos/prediction/elecpriceakkudoktor.py

The electricity price prediction provided prices in Eurocent/ kWh despite claiming the price to be in €/ kWh. Also the addition of charges was not possible.
Now prices are provided in €/kWh. Charges can be configured by the `elecprice_charges` configuration option.

Fix electricity price prediction.

---

README.md
pyproject.toml

Clean install of EOS with Python 3.9 requires Python 3.10 due to [numpy dependency](https://pypi.org/project/numpy/2.2.0/).
```
C:\Users\****\Desktop\EOS>.venv\Scripts\pip install -r requirements.txt
ERROR: Ignored the following versions that require a different python version: 2.1.0 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10; 2.1.1 Requires-Python >=3.10; 2.1.2 Requires-Python >=3.10; 2.1.3 Requires-Python >=3.10; 2.2.0 Requires-Python >=3.10; 2.2.0rc1 Requires-Python >=3.10; 2.2.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement numpy==2.2.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, …
```

numpy requires python version 3.10, requirement was 3.9

---

docs/akkudoktoreos/openapi.json
src/akkudoktoreos/core/dataabc.py
src/akkudoktoreos/server/fastapi_server.py

* Provider /v1/prediction/update and /v1/prediction/update/{provider_id} as POST endpoints to update provider data.
* Update description for deprecated endpoints how to use new API.

Prediction: Support manual update

---

src/akkudoktoreos/prediction/elecpriceakkudoktor.py
src/akkudoktoreos/prediction/predictionabc.py

Prediction providers can now individually set the minimum historic prediction hours to be kept in the data records. This setting supersedes any lower setting given by the configuration `prediction_historic_hours`.
As a help for the future change of ElecPriceAkkudoktor, the minimum historic hours for this provider is set to 5 * 7 * 24 hours.

Add minimum historic prediction hours for prediction providers.

---

scripts/extract_markdown.py
scripts/generate_config_md.py
scripts/generate_openapi.py
scripts/generate_openapi_md.py
tests/test_doc.py
tests/test_pvforecastakkudoktor.py
tests/test_weatherclearoutside.py

Read and write text files with utf8 encoding.
Maybe fixes #347. To be tested by someone with Windows.

Assert text files are in utf8

---

src/akkudoktoreos/prediction/elecpriceakkudoktor.py

The tests for test_elecpriceakkudoktor.py fail for 2 cases when I run them all at once. However, when I restart the failing tests individually, the error disappears.
I traced the issue to the fact that the forecast hours being requested are negative. This means we somehow have more forecast data in the API response than we originally requested.
What should we do in such cases? Should we enforce the forecast to 0 hours? Should we remove the data from the record that goes too far into the future? How problematic is it if we have more data in the record than we expected, e.g., based on prediction_hours?
This fix would keep the data in the cache but does not try to run a prediction with negative or 0 needed_prediction_hours

test_elecpriceakkudoktor bugfix

---

src/akkudoktoreos/utils/visualize.py

visualize.py is now using the timesone in the config.
visualized data should now be always in the tz of the system which is optimized and not the tz of the server calculating it.

tz for visualize.py

---

docs/develop/getting_started.md

doku fix
`config.json` is named `EOS.config.json`

EOS_DIR checks for an existing EOS.config.json

---

src/akkudoktoreos/utils/visualize.py

we need to use the backend if we don't have a gui in matplotlib
https://matplotlib.org/stable/users/explain/figure/backends.html
we cant use python-tk ([tkinter](https://docs.python.org/3/library/tkinter.html#module-tkinter))

fix for #375

---

Makefile
README.md
docs/develop/getting_started.md
src/akkudoktoreos/server/eos.py
src/akkudoktoreos/server/eosdash.py

Revert to EOSdash startup as a sub-process.
Add arguments to control the complete startup of both servers. Also development reload can now be given as an argument.
Closes #324
Closes #388

Fix EOSdash startup.

---

single_test_optimization.py

no inverter definition was made. properly relied on default settings which are not there anymore. which is a good thing. since the inverter should never be defaulted

fix for single_test_optimization.py

---

Dockerfile
src/akkudoktoreos/server/eos.py
src/akkudoktoreos/server/eosdash.py

* Need to start within container with host 0.0.0.0 to access it later on host.
EOSdash support for docker comes with #389 (sesskey fix)

Fix docker access. Closes #278

---

tests/test_elecpriceakkudoktor.py
tests/test_pvforecastakkudoktor.py

Adding an info text before intentional error messages are shown.
Closes #416

Info text for intentional errors

---

docs/_generated/openapi.md
openapi.json
src/akkudoktoreos/config/config.py
src/akkudoktoreos/core/ems.py
src/akkudoktoreos/core/pydantic.py
src/akkudoktoreos/prediction/predictionabc.py
src/akkudoktoreos/server/eos.py
tests/test_config.py
tests/test_dataabc.py
tests/test_elecpriceakkudoktor.py
tests/test_weatherbrightsky.py

* /v1/config/{path} supports setting single config value (post body). Lists are supported as well by using the index:
- general/latitude (value: 55.55)
- optimize/ev_available_charge_rates_percent/0 (value: 42)
Whole tree can be overriden as well (no merge):
- optimize/ev_available_charge_rates_percent (value: [42, 43, 44])

REST: Allow setting single config value

---

src/akkudoktoreos/config/config.py
src/akkudoktoreos/core/logging.py

* Support setting logger level (env) before config load.

Config: Don't fail on config error, fix Windows config dir

---

src/akkudoktoreos/utils/visualize.py

I tried to fix the problem with the timestamps in the diagrams. The discussion you can find in #387.

visualize: fix timestamps on diagramms

---

CONTRIBUTING.md
Dockerfile
README.md
docker-compose.yaml
docs/develop/getting_started.md
src/akkudoktoreos/server/eos.py
src/akkudoktoreos/server/eosdash.py
src/akkudoktoreos/server/server.py

* On Windows use 127.0.0.1 as default config host (model defaults) and
addionally redirect 0.0.0.0 to localhost on Windows (because default
config file still has 0.0.0.0).
Use 0.0.0.0 as default otherwise (e.g. Linux/Docker) to allow EOS
being accessible on local network (not just same host).
Note: Docs generation on Windows is incompatible with the Github
pipeline tests. Address this in the nested-config feature branch.
* Update install/startup instructions as package installation is
required atm and Docker on Windows has to be accessed at localhost or
127.0.0.1 even though the server log says 0.0.0.0 (which is required
to be available outside the container).
* Fix EOSdash startup with read_only: true (support session key via
EOS_SERVER__EOSDASH_SESSKEY variable). Backport of feature …

Windows: Fix EOSdash startup Closes #436 #447

---

scripts/generate_config_md.py
src/akkudoktoreos/config/config.py
src/akkudoktoreos/core/decorators.py

* Use own classproperty (don't inherit from property).
* Config generation: Rename pathlib._local to pathlib

Fix Python 3.13: classmethod + property unsupported

---

Dockerfile

* This allows to start the container without any extra settings (potentially unsafe). It is recommended to set EOS_SERVER__EOSDASH_SESSKEY.

Dockerfile: Set default for EOS_SERVER__EOSDASH_SESSKEY Closes #447

---

CONTRIBUTING.md

Fix take over the same link as in README.md. The current link will end up in HTTP error 404 (not found).

CONTRIBUTING.md fix documentation link (404 error)

---

.github/workflows/stale.yml

Add GitHub workflow to close requests/issues after 60 days of inactivity. Requests/ issues may be blocked from closing by adding the In progress label.

Close stale pull requests/ issues after 60 days

---

Makefile
docs/_generated/config.md
openapi.json
src/akkudoktoreos/config/config.py
src/akkudoktoreos/core/pydantic.py
src/akkudoktoreos/prediction/pvforecast.py
src/akkudoktoreos/server/dash/admin.py
src/akkudoktoreos/server/dash/components.py
src/akkudoktoreos/server/dash/configuration.py
src/akkudoktoreos/server/eos.py
tests/test_config.py
tests/test_datetimeutil.py
tests/test_eosdashconfig.py
tests/test_pvforecast.py
tests/test_pydantic.py

* Allow to configure planes and configuration values of planes separatedly.
Make single configuration values for planes explicitly available for configuration.
Still allows to also configure a plane by a whole plane value struct.
* Enhance admin page by file import and export of the EOS configuration
The actual EOS configuration can now be exported to the EOSdash server.
From there it can be also imported. For security reasons only import and export
from/ to a predefined directory on the EOSdash server is possible.
* Improve handling of nested value pathes in pydantic models.
Added separate methods for nested path access (get_nested_value, set_nested_value).
On value setting the missing fields along the nested path are now added automatically
and initialized with default values. Nested …

EOSdash: Improve PV forecast configuration.

---

.gitlint
.pre-commit-config.yaml
CONTRIBUTING.md
Makefile
requirements-dev.txt
scripts/gitlint/eos_commit_rules.py

Lint commit messages using gitlint in pre-commit.
Gitlint enforces rules that are configured by .gitlint.
The checks enforce the [`Conventional Commits`](https://www.conventionalcommits.org) commit message style.

ci: lint commit messages

---

.github/workflows/stale.yml

Wait 90 days until stale indication, wait another 30 days until closing. Excempt "enhancement" and "feature request" issues from stale handling. Excempt "in progress" pull requests from stale handling.

fix: relax stale issue/pr handling

---

src/akkudoktoreos/utils/datetimeutil.py
tests/test_datetimeutil.py

This PR fixes a potential ReDoS vulnerability in the `to_duration()` function.
Instead of restructuring the regex (which could break multi-part duration strings like "2 days 5 hours"), this fix introduces a clear and robust mitigation: a maximum input length check at the start of the function.
Includes:
- Max length check (`MAX_DURATION_STRING_LENGTH = 350`)
- Dedicated unit test to validate correct error and boundary behavior
Thanks @aydinnyunus for reporting and analyzing the issue (#494).

fix: mitigate ReDoS in to_duration via max input length check (closes #494)

---

README.md

On my windows device the following code was additionally needed to start the virtial environment:
.venv\Scripts\Activate
So I added it to the installation documentation.
Maybe the same is needed on Linux, but not tested from my side.

Activation of venv is needed

---

src/akkudoktoreos/prediction/weatherbrightsky.py

Make the BrightSky weather forecast more robust for the case that BrightSky does not provide relative humidity data for a certain location.
Fixes: #552

fix: BrightSky with None humidity data

---

docs/_generated/config.md
openapi.json
src/akkudoktoreos/prediction/pvforecast.py
src/akkudoktoreos/prediction/pvforecastakkudoktor.py
src/akkudoktoreos/server/dash/data/democonfig.json
tests/test_eosdashconfig.py
tests/test_pvforecastakkudoktor.py
tests/testdata/eosserver_config_1.json

EOS now enforces the general azimuth definition as e.g. defined in ISO 19111: north=0, east=90, south=180, west=270. This is the convention that is and was in the EOS documentation.
As the PV forecast of akkudoktor.net follows a different convention (north=+-180, east=-90, south=0, west=90) the values from EOS are now converted before the request is sent to akkudoktor.net.
BREAKING CHANGE: Azimuth configurations that followed the PVForecastAkkudoktor convention (north=+-180, east=-90, south=0, west=90) must be converted to the general azimuth definition: north=0, east=90, south=180, west=270.
Fixes: #564

fix: azimuth setting of pvforecastakkudoktor provider

---

tests/testdata/optimize_input_2.json

I found this empty inverter (without device id etc.) in the testdata. I think that happened when merging.

fix: delete empty inverter from testdata optimize_input_2.json

---

docs/akkudoktoreos/prediction.md
src/akkudoktoreos/prediction/elecpriceenergycharts.py

Hi, small fix for ElecPriceEnergyCharts:
- get lowest datetime in history by using key_to_series (with index)
- update docs with more information
Have a nice day

fix(ElecPriceEnergyCharts): get history series, update docs

---

Dockerfile

Fixes the issue where EOSDash is not accessible when running EOS in a Docker container. The problem was that EOSDash was binding to 127.0.0.1 (localhost) by default, making it inaccessible from outside the container.
The fix adds a minimal default configuration file during the Docker image build that sets both the EOS server and EOSDash to bind to 0.0.0.0, allowing external access while maintaining security through Docker's network isolation.
- Add default EOS.config.json in Dockerfile with server bindings set to 0.0.0.0
- No changes required to docker-compose.yaml
- Ensures EOSDash works out of the box for Docker users
Fixes: #629
Closes: https://github.com/Akkudoktor-EOS/EOS/issues/629

fix(docker): make EOSDash accessible in Docker containers

---

docker-compose.yaml

This PR addresses issue #661 by adding clear documentation to the docker-compose.yaml file about the configuration requirements when using volume mounts.
Problem:  
When users mount local directories to the Docker container, the default configuration file created during the Docker build phase is overridden. This causes the frontend to become inaccessible because the server binds to 127.0.0.1 instead of 0.0.0.0. Users will typically add their volume mounts directly in the docker-compose.yaml file, but if they are not aware that they need a specific configuration with 0.0.0.0 bindings, they will  encounter connection issues and the dashboard becomes inaccessible.
Solution
Added comprehensive documentation in docker-compose.yaml that:
- Explains why the default config is lost when mounting …

docs: Add Docker volume mount configuration instructions
